### ISSUE TITLE
"tokens" file for revokable access

### ISSUE THREAD

**Issue by robb-j** [digitalinteraction/data-officer#3]
There could be a file, like `auth_tokens.json` inside the container that the `auth.authenticate` could also check for hard-coded access to scopes that can be revoked by removing them from the file. e.g. (yaml for brevity)

> It could also be YAML as Deno supports it first-class

```yml
- name: coffee-club-bot
  enabled: true
  token: 920208d2a624576d150cb4247425d9a5
  scopes:
    - repos:openlab:people

- name: coffee-dashboard
  enabled: false
  token: 02b15fd6553af93969ba602b71cbebe7
  scopes:
    - repos:coffee-club

- name: uptimerobot
  enabled: true
  token: 7278afc69bfa4399f1141437f8ef551a
  scopes:
    - ping

- name: rob
  enabled: true
  token: 8b747a046619c600c869e4268670a086
  scopes:
    - admin
```
